version: '3'
services:
  tts-generation-webui:
    image: "ghcr.io/rsxdalv/tts-generation-webui:main"
    restart: unless-stopped
    ports:
      - "7860:7860"
      # include React UI
      - "3000:3000"
    container_name: tts-generation-webui
    deploy:
        resources:
          reservations:
            devices:
              - driver: nvidia
                device_ids: ['0']
                capabilities: [gpu]
