services:
  tts-generation-webui:
    image: "ghcr.io/rsxdalv/tts-generation-webui:main"
    restart: unless-stopped
    ports:
      - "7770:7770"
      # include React UI
      - "3000:3000"
    container_name: tts-generation-webui
    deploy:
        resources:
          reservations:
            devices:
              - driver: nvidia
                device_ids: ['0']
                capabilities: [gpu]

  # for the future:
  # db:
  #   image: postgres
  #   restart: always
  #   environment:
  #     POSTGRES_PASSWORD: example
  #   healthcheck:
  #     test: ["CMD-SHELL", "pg_isready"]
  #     interval: 1s
  #     timeout: 5s
  #     retries: 10
 